---
- name: Setup OpenStack infrastructure
  hosts: localhost
  collections:
    - openstack.cloud
  tasks:
    - network:
        state: present
        name: web_tier
    - subnet:
        state: present
        network_name: web_tier
        name: web_tier
        cidr: 10.0.0.0/24
    - network:
        state: present
        name: db_tier
    - subnet:
        state: present
        network_name: db_tier
        name: db_tier
        cidr: 10.0.1.0/24
    - router:
        state: present
        name: ansible-router
        network: External
        interfaces:
          - net: web_tier
            subnet: web_tier
            portip: 10.0.0.1
          - net: db_tier
            subnet: db_tier
            portip: 10.0.1.1
    - security_group:
        state: present
        name: web_tier_jumpstation
        description: "Web Tier Jumpstation access"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        security_group: web_tier_jumpstation
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
    - security_group:
        state: present
        name: web_tier_dev
        description: "Web Tier development server access"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        security_group: web_tier_dev
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_group: web_tier_jumpstation
    - security_group:
        state: present
        name: web_tier
        description: "Access to Web Instances"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: web_tier
        port_range_min: 22
        port_range_max: 22
        remote_group: web_tier_jumpstation
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: web_tier
        port_range_min: 22
        port_range_max: 22
        remote_group: web_tier_dev
    - security_group:
        state: present  
        name: public_http
        description: "Public HTTP traffic to the load balancer"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: public_http
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0
    - security_group:
        state: present
        name: "http_from_load_balancer"
        description: "HTTP traffic from load balancer to web_tier"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: web_tier
        port_range_min: 80
        port_range_max:  80
        remote_group: public_http
    - security_group:
        state: present
        name: public_https
        description: "Public HTTPS traffic to the load balancer"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: public_https
        port_range_min: 443
        port_range_max: 443
        remote_ip_prefix: 0.0.0.0/0
    - security_group:
        state: present
        name: https_from_load_balancer
        description: "HTTPS traffic from load balancer to web_tier"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: https_from_load_balancer
        port_range_min: 443
        port_range_max: 443
        remote_group: public_https
    - security_group:
        state: present
        name: db_tier_jumpstation
        description: "SSH access to DB Tier Jumpstation from Web Tier jumpstation"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: db_tier_jumpstation
        port_range_min: 22
        port_range_max: 22
        remote_group: web_tier_jumpstation
    - security_group:
        state: present
        name: db_tier
        description: "Access to DB tier instances"
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: db_tier
        port_range_min: 22
        port_range_max: 22
        remote_group: db_tier_jumpstation
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: db_tier
        port_range_min: 3306
        port_range_max: 3306
        remote_group: web_tier
    - security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: db_tier
        port_range_min: 3306
        port_range_max: 3306
        remote_group: db_tier