---
- name: Setup OpenStack infrastructure
  hosts: localhost
  vars:
    instance_image: "CentOS 7 (el7-x86_64)"
    instance_key: work
  collections:
    - openstack.cloud
  tasks:
    - name: "Create web_tier network"
      network:
        state: present
        name: web_tier
    - name: "Create web_tier subnet"
      subnet:
        state: present
        network_name: web_tier
        name: web_tier
        cidr: 10.0.0.0/24
    - name: "Create db_tier network"
      network:
        state: present
        name: db_tier
    - name: "Create db_tier subnet"
      subnet:
        state: present
        network_name: db_tier
        name: db_tier
        cidr: 10.0.1.0/24
    - name: "Create router with web_tier and db_tier interfaces"
      router:
        state: present
        name: ansible-router
        network: External
        interfaces:
          - net: web_tier
            subnet: web_tier
            portip: 10.0.0.1
          - net: db_tier
            subnet: db_tier
            portip: 10.0.1.1
    - name: "Create web_tier_jumpstation security group"
      security_group:
        state: present
        name: web_tier_jumpstation
        description: "Web Tier Jumpstation access"
    - name: "Create SSH rule for web_tier_jumpstation security group"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        security_group: web_tier_jumpstation
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
    - name: "Create web_tier_dev security group"
      security_group:
        state: present
        name: web_tier_dev
        description: "Web Tier development server access"
    - name: "Create SSH rule for web_tier_dev security group"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        security_group: web_tier_dev
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_group: web_tier_jumpstation
    - name: "Create web_tier security group"
      security_group:
        state: present
        name: web_tier
        description: "Access to Web Instances"
    - name: "Create SSH rule for web_tier from web_tier_jumpstation"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: web_tier
        port_range_min: 22
        port_range_max: 22
        remote_group: web_tier_jumpstation
    - name: "Create SSH rule for web_tier from web_tier_dev"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: web_tier
        port_range_min: 22
        port_range_max: 22
        remote_group: web_tier_dev
    - name: "Create public_http security group"
      security_group:
        state: present  
        name: public_http
        description: "Public HTTP traffic to the load balancer"
    - name: "Create HTTP rule for public_http security group from all IPs"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: public_http
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0
    - name: "Create http_from_load_balancer security group"
      security_group:
        state: present
        name: "http_from_load_balancer"
        description: "HTTP traffic from load balancer to web_tier"
    - name: "Create HTTP rule for http_from_load_balancer security group from public_http security group"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: http_from_load_balancer
        port_range_min: 80
        port_range_max:  80
        remote_group: public_http
    - name: "Create public_https security group"
      security_group:
        state: present
        name: public_https
        description: "Public HTTPS traffic to the load balancer"
    - name: "Create HTTPS rule for public_https security group from all IPs"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: public_https
        port_range_min: 443
        port_range_max: 443
        remote_ip_prefix: 0.0.0.0/0
    - name: "Create https_from_load_balancer security group"
      security_group:
        state: present
        name: https_from_load_balancer
        description: "HTTPS traffic from load balancer to web_tier"
    - name: "Create HTTPS rule for https_from_load_balancer security from public_https security group"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: https_from_load_balancer
        port_range_min: 443
        port_range_max: 443
        remote_group: public_https
    - name: "Create db_tier_jumpstation security group"
      security_group:
        state: present
        name: db_tier_jumpstation
        description: "SSH access to DB Tier Jumpstation from Web Tier jumpstation"
    - name: "Create SSH rule for db_tier_jumpstation security group from web_tier_jumpstation security group"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: db_tier_jumpstation
        port_range_min: 22
        port_range_max: 22
        remote_group: web_tier_jumpstation
    - name: "Create db_tier security group"
      security_group:
        state: present
        name: db_tier
        description: "Access to DB tier instances"
    - name: "Create SSH rule for db_tier security group from db_tier_jumpstation security group"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: db_tier
        port_range_min: 22
        port_range_max: 22
        remote_group: db_tier_jumpstation
    - name: "Create MySQL rule for db_tier security group from web_tier security group"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: db_tier
        port_range_min: 3306
        port_range_max: 3306
        remote_group: web_tier
    - name: "Create MySQL rule for db_tier security group from db_tier security group"
      security_group_rule:
        state: present
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        security_group: db_tier
        port_range_min: 3306
        port_range_max: 3306
        remote_group: db_tier
    - name: "Create web_tier_jumpstation instance"
      server:
        state: present
        name: "web_tier_jumpstation"
        image: "{{ instance_image }}"
        key_name: "{{ instance_key }}"
        flavor: c1.micro
        network: web_tier
        auto_ip: no
        security_groups:
          - web_tier_jumpstation