---
- name: Setup OpenStack infrastructure
  hosts: localhost
  collections:
    - openstack.cloud
  tasks:
    - network:
        state: present
        name: web_tier
    - subnet:
        state: present
        network_name: web_tier
        name: web_tier
        cidr: 10.0.0.0/24
    - network:
        state: present
        name: db_tier
    - subnet:
        state: present
        network_name: db_tier
        name: db_tier
        cidr: 10.0.1.0/24
    - router:
        state: present
        name: ansible-router
        network: External
        interfaces:
          - net: web_tier
            subnet: web_tier
            portip: 10.0.0.1
          - net: db_tier
            subnet: db_tier
            portip: 10.0.1.1
